# The session secret key (`apg -m 64` is always useful for this kinda stuff)
cookie_secret: ssssht

# The path where git repositories are stored. The actual (bare) repositories resides
# in repository_base_path/#{project.slug}/#{repository.name}.git/:
repository_base_path: "/path/to/gitorious/repositories"

# Stuff that's in the html <head>. custom stats javascript code etc
extra_html_head_data: 
  
# System message that will appear on all pages if present
system_message: 
  
# Port the ./script/gitorious script should use:
gitorious_client_port: 3000

# Host the ./script/gitorious script should use:
gitorious_client_host: localhost

# Host which is serving the gitorious app, eg "gitorious.org"
gitorious_host: gitorious.org
