# The session secret key (`apg -m 64` is always useful for this kinda stuff)
cookie_secret: ssssht

# The path where git repositories are stored. The actual (bare) repositories resides
# in repository_base_path/#{project.slug}/#{repository.name}.git/:
repository_base_path: "/path/to/gitorious/repositories"

# Stuff that's in the html <head>. custom stats javascript code etc
extra_html_head_data: 
  
# System message that will appear on all pages if present
system_message: 
  
# Port the ./script/gitorious script should use:
gitorious_client_port: 3000

# Host the ./script/gitorious script should use:
gitorious_client_host: localhost

# Host which is serving the gitorious app, eg "gitorious.org"
gitorious_host: gitorious.org

# User which is running git daemon
gitorious_user: git

# Email spam on server errors to:
exception_notification_emails:  

# Mangle visible e-mail addresses (spam protection)
mangle_email_addresses: true

# Enable or Disable Public Mode (true) or Private Mode (false)
public_mode: true

# Define your locale
locale: en

# Where so we store generated tarballs?
# (should be readable by webserver, since we tell it to send the file using X-Sendfile)
archive_cache_dir: "/path/to/tarballs-cache"
# Which directory should we work in when we generate tarballs, before moving 
# them to the above dir?
archive_work_dir: "/path/to/tarballs-work"
